-- CREANDO LA BASE DE DATOS DEL DATA WAREHOUSE
CREATE DATABASE DWH_HM
GO

USE DWH_HM
GO

-- DIMENSION: DIM_PACIENTE
CREATE TABLE DIM_PACIENTE (
    IDPACIENTE CHAR(8) NOT NULL PRIMARY KEY,
    NOMBREP VARCHAR(100),
    APELLIDOP VARCHAR(100),
    GENEROP CHAR(1),
    EDAD INT,
    DIRECCIONP VARCHAR(100),
    NUMTELEFONICOP VARCHAR(15)
)
GO

-- DIMENSION: DIM_MEDICO
CREATE TABLE DIM_MEDICO (
    IDMEDICO CHAR(8) NOT NULL PRIMARY KEY,
    NOMBREM VARCHAR(100),
    APELLIDOM VARCHAR(100),
    ESPECIALIDADM VARCHAR(100),
    EXPERIENCIAM VARCHAR(100),
    TELEFONOM VARCHAR(15),
    EMAILM VARCHAR(40)
)
GO

-- DIMENSION: DIM_ENFERMERO
CREATE TABLE DIM_ENFERMERO (
    IDENFERMERO CHAR(8) NOT NULL PRIMARY KEY,
    NOMBREENF VARCHAR(100),
    ESPECIALIDADENF VARCHAR(100),
    EXPERIENCIAENF VARCHAR(100),
    TELEFONOENF VARCHAR(15),
    EMAILM VARCHAR(40)
)
GO

-- DIMENSION: DIM_ENFERMEDAD
CREATE TABLE DIM_ENFERMEDAD (
    NOMBREENF CHAR(100) NOT NULL PRIMARY KEY,
    CAUSASENF CHAR(300),
    COMPLICACIONESENF CHAR(300),
    GRAVEDADENF CHAR(100)
)
GO

-- DIMENSION: DIM_TRATAMIENTO
CREATE TABLE DIM_TRATAMIENTO (
    IDTRATAMIENTO CHAR(8) NOT NULL PRIMARY KEY,
    NOMBREMED CHAR(100),
    NOMBRETR CHAR(100),
    FECHAINI DATE,
    FECHAFIN DATE,
    DESCTRA CHAR(300),
    SUJETOTRA CHAR(100)
)
GO

-- DIMENSION: DIM_TIEMPO
CREATE TABLE DIM_TIEMPO (
    FECHA_ID INT PRIMARY KEY,
	ANIO INT,
	TRIMESTRE INT,
	MES INT,
	NOM_MES VARCHAR(15),
	DIA VARCHAR,
	DIA_SEM INT,
	NOM_DIA_SEM VARCHAR(15)
);

GO

-- TABLA DE HECHOS: FACT_CONSULTAS
CREATE TABLE FACT_CONSULTAS (
    IDCONSULTA CHAR(8) NOT NULL PRIMARY KEY,
    IDPACIENTE CHAR(8) NOT NULL,
    IDMEDICO CHAR(8) NOT NULL,
	FECHA_ID INT NOT NULL,
    IDENFERMERO CHAR(8),
    NOMBREENF CHAR(100),
    IDTRATAMIENTO CHAR(8)
               
    --DURACION_MIN INT,
    --ESTADO BIT DEFAULT 1,
    FOREIGN KEY(IDPACIENTE) REFERENCES DIM_PACIENTE(IDPACIENTE),
    FOREIGN KEY(IDMEDICO) REFERENCES DIM_MEDICO(IDMEDICO),
    FOREIGN KEY(IDENFERMERO) REFERENCES DIM_ENFERMERO(IDENFERMERO),
    FOREIGN KEY(NOMBREENF) REFERENCES DIM_ENFERMEDAD(NOMBREENF),
    FOREIGN KEY(IDTRATAMIENTO) REFERENCES DIM_TRATAMIENTO(IDTRATAMIENTO),
    FOREIGN KEY(FECHA_ID) REFERENCES DIM_TIEMPO(FECHA_ID) -- Relación con DIM_TIEMPO
)
GO



--INSERT DIM_PACIENTE-----------------------------------------------------------------------------
INSERT INTO DWH_HM.dbo.DIM_PACIENTE(IDPACIENTE, NOMBREP, APELLIDOP, GENEROP, EDAD, DIRECCIONP,NUMTELEFONICOP)
SELECT        IDPACIENTE, NOMBREP, APELLIDOP, GENEROP, EDAD, DIRECCIONP,NUMTELEFONICOP
FROM            BD_HM.dbo.PACIENTE

/*
select * from DIM_PACIENTE
*/

--INSERT DIM_MEDICO-----------------------------------------------------------------------------
INSERT INTO DWH_HM.dbo.DIM_MEDICO(IDMEDICO, NOMBREM, APELLIDOM, ESPECIALIDADM, EXPERIENCIAM, TELEFONOM,EMAILM)
SELECT        IDMEDICO, NOMBREM, APELLIDOM, ESPECIALIDADM, EXPERIENCIAM, TELEFONOM,EMAILM
FROM            BD_HM.dbo.MEDICO

/*
select * from DIM_MEDICO
*/


--INSERT DIM_ENFERMERO-----------------------------------------------------------------------------
INSERT INTO DWH_HM.dbo.DIM_ENFERMERO(IDENFERMERO, NOMBREENF, ESPECIALIDADENF, EXPERIENCIAENF, TELEFONOENF, EMAILM)
SELECT        IDENFERMERO, NOMBREENF, ESPECIALIDADENF, EXPERIENCIAENF, TELEFONOENF, EMAILM
FROM            BD_HM.dbo.ENFERMERO

/*
select * from DIM_ENFERMERO
*/

--INSERT DIM_ENFERMEDAD-----------------------------------------------------------------------------
INSERT INTO DWH_HM.dbo.DIM_ENFERMEDAD(NOMBREENF, CAUSASENF, COMPLICACIONESENF, GRAVEDADENF)
SELECT        NOMBREENF, CAUSASENF, COMPLICACIONESENF, GRAVEDADENF
FROM            BD_HM.dbo.ENFERMEDAD

/*
select * from DIM_ENFERMEDAD
*/



--INSERT DIM_TRATAMIENTO-----------------------------------------------------------------------------
INSERT INTO DWH_HM.dbo.DIM_TRATAMIENTO(IDTRATAMIENTO, NOMBREMED, NOMBRETR, FECHAINI,FECHAFIN,DESCTRA,SUJETOTRA)
SELECT        IDTRATAMIENTO, NOMBREMED, NOMBRETR, FECHAINI,FECHAFIN,DESCTRA,SUJETOTRA
FROM            BD_HM.dbo.TRATAMIENTO

/*
select * from DIM_TRATAMIENTO
*/


--INSERT DIM_TIEMPO-----------------------------------------------------------------------------

--CREAR función Fn_Mes
create function Fn_Mes(@mm int) returns varchar(15)
begin
	declare @meses table(cod int, nombre varchar(15))
	insert @meses values(1,'enero'),(2,'febrero'),(3,'marzo'),(4,'abril'),(5,'mayo'),(6,'junio'),
	(7,'julio'),(8,'agosto'),(9,'setiembre'),(10,'octubre'),(11,'noviembre'),(12,'diciembre')
	return (select nombre from @meses where cod=@mm)
end
go

--CREAR función Fn_dia
create function Fn_Dia (@dd int) returns varchar(15)
begin
	declare @semana table(cod int, nombre varchar(15))
	insert @semana values(1,'domingo'),(2,'lunes'),(3,'martes'),(4,'miercoles'),(5,'jueves'),
	(6,'viernes'),(7,'sabado')
	return (select nombre from @semana where cod=@dd)
end
go

-- INSERTAR DATOS DIMENSION DIM_TIEMPO
insert DWH_HM.dbo.DIM_TIEMPO
select distinct 
year(FECHA_HORA_CONSULTA)*10000+month(FECHA_HORA_CONSULTA)*100+day(FECHA_HORA_CONSULTA), 
year(FECHA_HORA_CONSULTA) as ANIO, 
datepart (quarter,FECHA_HORA_CONSULTA) as TRIMESTRE,
month (FECHA_HORA_CONSULTA) as MES, 
DWH_HM.dbo.Fn_Mes(month(FECHA_HORA_CONSULTA)) as NOM_MES,
day(FECHA_HORA_CONSULTA) as DIA, 
DATEPART(WEEKDAY, FECHA_HORA_CONSULTA) as DIA_SEM,
DWH_HM.dbo.Fn_dia(DATEPART(weekday, FECHA_HORA_CONSULTA)) as NOM_DIA_SEM
from BD_HM.dbo.CONSULTA


GO



/*
select * from DIM_TIEMPO
*/


--INSERT FACT_CONSULTAS-----------------------------------------------------------------------------

INSERT INTO DWH_HM.dbo.FACT_CONSULTAS (
    IDCONSULTA,
    IDPACIENTE,
    IDMEDICO,
    FECHA_ID,
    IDENFERMERO,
    NOMBREENF,
    IDTRATAMIENTO
)
SELECT
    C.IDCONSULTA,                             
    C.IDPACIENTE,
    C.IDMEDICO,	
    YEAR(C.FECHA_HORA_CONSULTA) * 10000 + 
    MONTH(C.FECHA_HORA_CONSULTA) * 100 + 
    DAY(C.FECHA_HORA_CONSULTA) AS FECHA_ID,
    T.IDENFERMERO,
    D.NOMBREENF,
    D.IDTRATAMIENTO
FROM 
    BD_HM.dbo.CONSULTA AS C
LEFT JOIN 
    BD_HM.dbo.TRIAJE AS T ON C.IDCONSULTA = T.IDCONSULTA 
LEFT JOIN 
     BD_HM.dbo.DIAGNOSTICO AS D ON C.IDCONSULTA = D.IDCONSULTA 

WHERE 
    C.FECHA_HORA_CONSULTA IS NOT NULL 


GO


/*
select * from FACT_CONSULTAS



DELETE FACT_CONSULTAS
DELETE DIM_PACIENTE
DELETE DIM_MEDICO
DELETE DIM_ENFERMERO
DELETE DIM_ENFERMEDAD
DELETE DIM_TRATAMIENTO
DELETE DIM_TIEMPO




SELECT * FROM  DIM_PACIENTE
SELECT * FROM  DIM_MEDICO
SELECT * FROM  DIM_ENFERMERO
SELECT * FROM  DIM_ENFERMEDAD
SELECT * FROM  DIM_TRATAMIENTO
SELECT * FROM  DIM_TIEMPO
SELECT * FROM FACT_CONSULTAS


*/



